// Generated by CodiumAI

import { mashamba } from "./mashamba";

describe('mashamba', () => {

});

    // Load and display the first page of a document
    it('should load and display the first page of a document', () => {
      // Create an instance of the 'mashamba' class
      const mashambaInstance = new mashamba();

      // Mock the 'server.exec' method to return a sample document data
      jest.spyOn(server, 'exec').mockResolvedValue([
        {
          pages: JSON.stringify([
            { url: 'http://example.com/image1.jpg' },
            { url: 'http://example.com/image2.jpg' },
            { url: 'http://example.com/image3.jpg' }
          ])
        }
      ]);

      // Mock the 'document.getElementById' method to return the required elements
      jest.spyOn(document, 'getElementById').mockImplementation((id: string) => {
        const element = document.createElement('input');
        element.id = id;
        return element;
      });

      // Call the 'show_panels' method to load the document data and display the first page
      mashambaInstance.show_panels();

      // Assert that the first page image is created and its source is set correctly
      const firstPageImage = mashambaInstance.first_page.querySelector('.image');
      expect(firstPageImage).toBeTruthy();
      expect(firstPageImage!.src).toBe('http://example.com/image1.jpg');
    });

